module.exports = Object.freeze({
  mConstants: {
    envFilename: "env.json",
    appName: "Accubridge"
  },
  seed: {
    app_data: [
      { "field": "additional_fields", mValue: "[]" },
      { field: "date_format", mValue: "dd-MM-yyyy hh:mm" },
      { "field": "enableInbound", "mValue": "true" },
      { "field": "enableOutbound", "mValue": "false" },
      { "field": "enableOutboundExport", "mValue": "true" },
      { "field": "enableOutboundDomestic", "mValue": "true" },
      { "field": "enableOutboundSubcontract", "mValue": "true" },
      { "field": "enableOthers", "mValue": "true" },
      { "field": "enableInternal", "mValue": "false" },
      { field: "enableWhiteSpacesInVehicle", "mValue": "false" },
      { field: "enableWeightEditing", "mValue": "false" },
      { field: "enterFirstWeightManually", "mValue": "false" },
      { field: "enableWeighmentTypes", "mValue": "yes" },
      { field: "logLevel", mValue: "error" },
      { field: "enable_invoice_creation", mValue: "true" },
      { field: "enable_inbound_challan_weight", mValue: "false" },
      { field: "enable_inbound_validation", mValue: "false" },
      { field: "inbound_upper_limit", mValue: "" },
      { field: "inbound_lower_limit", mValue: "" },
      { field: "inbound_on_validation_failure", mValue: "Do not save" },
      { field: "enable_outbound_challan_weight", mValue: "false" },
      { field: "enable_outbound_validation", mValue: "false" },
      { field: "outbound_upper_limit", mValue: "" },
      { field: "outbound_lower_limit", mValue: "" },
      { field: "outbound_on_validation_failure", mValue: "Do not save" },
      { field: "enable_inbound_outbound", mValue: "true" },
      { field: "enable_internal_weight", mValue: "true" },
      { field: "enable_data_edit_after_completion", mValue: "false" },
      { field: "data_edit_reason_length", mValue: "200" },
      { field: "min_vehicle_length", mValue: "8" },
      { field: "min_reciept_length", mValue: "4" },
      { field: "save_on_zero_weight", mValue: "false" },
      { field: "enable_zero_check", mValue: "false" },
      { field: "zero_tolerance", mValue: "0" },
      { field: "allow_zero_net_weight", mValue: "false" },
      { field: "net_weight_fluctuation", mValue: "0" },
      { field: "enable_stable_weight", mValue: "true" },
      { field: "allowed_variation", mValue: "0" },
      { field: "enable_auto_print_post_weighment", mValue: "false" },
      { field: "print_cnt_post_weight1", mValue: "1" },
      { field: "print_cnt_post_weight2", mValue: "1" },
      { field: "report_header_1", mValue: "" },
      { field: "report_header_2", mValue: "" },
      { field: "report_print_current_date", mValue: "false" },
      { field: "report_print_search_params", mValue: "false" },
      { field: "report_readonly", mValue: "false" },
      { field: "is_report_password_protected", mValue: "false" },
      { field: "report_password", mValue: "" },
      { field: "report_date_format", mValue: "dd-MM-yyyy" },
      { field: "report_time_format", mValue: "HH:mm" },
      { field: "currency", mValue: "" },
      { field: "decimals_in_weight", mValue: "" },
      { field: "enable_scheduled_backup", mValue: "false" },
      { field: "backup_location", mValue: "" },

      //Email setup
      { field: "allow_email", mValue: "false" },
      { field: "enable_daily_email", mValue: "false" },
      { field: "daily_email_time", mValue: "" },
      { field: "enable_daily_operator_collection_email", mValue: "false" },
      { field: "collection_email_time", mValue: "" },
      { field: "email_provider", mValue: "" },
      { field: "email_condition", mValue: "" },
      { field: "sender_email_id", mValue: "" },
      { field: "email_password", mValue: "" },
      { field: "sender_name", mValue: "" },
      { field: "email_server", mValue: "" },
      { field: "email_port", mValue: "" },
      { field: "email_protocol", mValue: "" },
      { field: "recipients", mValue: "" },

      //SAP Configuration
      { field: "enableSAPIntegration", mValue: "false" },
      { field: "sapUsername", mValue: "" },
      { field: "sapPassword", mValue: "" },
      { field: "sapEndpoint", mValue: "" }
    ],
    app_user: [{
      "id": 1,
      "username": "admin",
      "fullname": "Administrator",
      "role": "Admin",
      "password": "Admin123",
      "status": "Active"
    }, {
      "id": 2,
      "username": "test",
      "fullname": "Test User",
      "role": "Operator",
      "password": "Test123",
      "status": "Active"
    }
    ],
    permission: [
      { id: 1, permission: "Weighment" },
      { id: 2, permission: "System setup" },
      { id: 3, permission: "Ticket Setup" },
      { id: 4, permission: "Vehicle Setup" },
      { id: 5, permission: "Backup" },
      { id: 6, permission: "Data edit after complete weighment" },
      { id: 7, permission: "Theft detection report" },
      { id: 8, permission: "Reports" },
      { id: 9, permission: "Code and list entries" },
      { id: 10, permission: "User Management" },
      { id: 11, permission: "Change Password" },
      { id: 12, permission: "Partial Weighment" },
      { id: 13, permission: "Theft Detection Setup" },
      { id: 14, permission: "SAP Configuration" },
    ],
    user_permission: [
      { userid: 1, permissionid: 1},
      { userid: 1, permissionid: 2},
      { userid: 1, permissionid: 3},
      { userid: 1, permissionid: 4},
      { userid: 1, permissionid: 5},
      { userid: 1, permissionid: 6},
      { userid: 1, permissionid: 7},
      { userid: 1, permissionid: 8},
      { userid: 1, permissionid: 9},
      { userid: 1, permissionid: 10},
      { userid: 1, permissionid: 11},
      { userid: 1, permissionid: 12},
      { userid: 1, permissionid: 13 },
      { userid: 1, permissionid: 14 },
      { userid: 2, permissionid: 1},
      { userid: 2, permissionid: 2},
      { userid: 2, permissionid: 3},
    ],
    ticket_template: [
      {
        id: 1,
        name: "GENERIC",
        applicableTo: "GENERIC",
        printerType: "DOT-MATRIX",
        labelLength: 200,
        copiesPerPrint: 1,
        alignment: 'Horizontal',
        width: 200,
        font: "Arial",
        fontSize: 10,
        defaultPrinter: null,
        operatingType: null
      }
    ],
    template_detail: [
      { id: 1, templateId: 1, field: "transporterCode", type: "ticket-field", displayName: 'Tranporter Code', row: 7, col: 1, isIncluded: 1, font: "R" },
      {
        id: 2, templateId: 1, field: "transporterName", type: "ticket-field", displayName: 'Transporter Name', row: 6, col: 1, isIncluded: 1, font: "R"
      },
      {
        id: 3, templateId: 1, field: "scrollNo", type: "ticket-field", displayName: 'Scroll No', row: null, col: null, isIncluded: 1, font: "R"
      },
      {
        id: 4, templateId: 1, field: "rstNo", type: "ticket-field", displayName: 'Rst No', row: 4, col: 1, isIncluded: 1, font: "R"
      },
      {
        id: 5, templateId: 1, field: "vehicleNo", type: "ticket-field", displayName: 'Vehicle No', row: 5, col: 1, isIncluded: 1, font: "R"
      },
      {
        id: 6, templateId: 1, field: "reqId", type: "ticket-field", displayName: 'Request Id', row: null, col: null, isIncluded: 1, font: "R"
      },
      {
        id: 7, templateId: 1, field: "status", type: "ticket-field", displayName: 'status', row: null, col: null, isIncluded: 1, font: "R"
      },
      {
        id: 8, templateId: 1, field: "gatePassNo", type: "ticket-field", displayName: 'Gate Pass No.', row: null, col: null, isIncluded: 1, font: "R"
      },
      {
        id: 9, templateId: 1, field: "poDetails", type: "ticket-field", displayName: 'PO Details', row: null, col: null, isIncluded: 1, font: "R"
      },
      {
        id: 10, templateId: 1, field: "createdAt", type: "ticket-field", displayName: 'Created At', row: null, col: null, isIncluded: 1, font: "R"
      },
      {
        id: 11, templateId: 1, field: "duration", type: "ticket-field", displayName: 'Duration', row: null, col: null, isIncluded: 1, font: "R"
      },
      {
        id: 12, templateId: 1, field: "weighmentType", type: "ticket-field", displayName: 'Inbound / Outbound', row: null, col: null, isIncluded: 1, font: "R"
      },
      {
        id: 13, templateId: 1, field: "weighmentDetails", type: "ticket-field", displayName: 'Weighment Details', row: 12, col: 1, isIncluded: 1, font: "R"
      },
      {
        id: 14, templateId: 1, field: "weighDetails_id", type: "ticket-field", displayName: 'Weighslip No', row: null, col: null, isIncluded: 1, font: "R"
      },
      {
        id: 15, templateId: 1, field: "weighDetails_material", type: "ticket-field", displayName: 'Material', row: null, col: null, isIncluded: 1, font: "R"
      },
      {
        id: 16, templateId: 1, field: "weighDetails_supplier", type: "ticket-field", displayName: 'Supplier', row: 5, col: 40, isIncluded: 1, font: "R"
      },
      {
        id: 17, templateId: 1, field: "weighDetails_firstWeight", type: "ticket-field", displayName: 'Wt1(KG)', row: 8, col: 1, isIncluded: 1, font: "R"
      },
      {
        id: 18, templateId: 1, field: "weighDetails_firstWeightDatetime", type: "ticket-field", displayName: 'In Date / Time', row: 8, col: 40, isIncluded: 1, font: "R"
      },
      {
        id: 19, templateId: 1, field: "weighDetails_secondWeight", type: "ticket-field", displayName: 'Wt2(KG)', row: 9, col: 1, isIncluded: 1, font: "R"
      },
      {
        id: 20, templateId: 1, field: "weighDetails_secondWeightDatetime", type: "ticket-field", displayName: 'Out Date / Time', row: 9, col: 40, isIncluded: 1, font: "R"
      },
      {
        id: 21, templateId: 1, field: "weighDetails_netWeight", type: "ticket-field", displayName: 'Net Wt(KG)', row: 10, col: 1, isIncluded: 1, font: "R"
      },
      {
        id: 22, templateId: 1, field: null, type: "freetext", displayName: 'BHARAT FORGE LIMITED', row: 1, col: 30, isIncluded: 1, font:	"DB"
      },
      {
        id: 23, templateId: 1, field: null, type: "freetext", displayName: 'MUNDHWA, PUNE 411036', row: 2, col: 30, isIncluded: 1, font: "DB"
      },
      {
        id: 24, templateId: 1, field: null, type: "freetext", displayName: '---------------------------------------------------------------------------------', row: 3, col: 1, isIncluded: 1, font: "R"
      },
      {
        id: 25, templateId: 1, field: null, type: "freetext", displayName: '---------------------------------------------------------------------------------', row: 11, col: 1, isIncluded: 1, font: "R"
      },
      {
        id: 26, templateId: 1, field: "material", type: "weighment_detail", displayName: 'Material', row: null, col: 1, isIncluded: 0, font: "R"
      },
      {
        id: 27, templateId: 1, field: "supplier", type: "weighment_detail", displayName: 'Supplier', row: null, col: 1, isIncluded: 0, font: "R"
      },
      {
        id: 28, templateId: 1, field: "firstWeight", type: "weighment_detail", displayName: 'WT1', row: null, col: 2, isIncluded: 1, font: "R"
      },
      {
        id: 29, templateId: 1, field: "firstWeightDatetime", type: "weighment_detail", displayName: 'WT1 Datetime', row: null, col: 5, isIncluded: 1, font: "R"
      },
      {
        id: 30, templateId: 1, field: "secondWeight", type: "weighment_detail", displayName: 'WT2', row: null, col: 9, isIncluded: 1, font: "R"
      },
      {
        id: 31, templateId: 1, field: "firstUnit", type: "weighment_detail", displayName: 'WT1 Unit', row: null, col: 1, isIncluded: 0, font: "R"
      },
      {
        id: 32, templateId: 1, field: "secondUnit", type: "weighment_detail", displayName: 'WT2 Unit', row: null, col: 1, isIncluded: 0, font: "R"
      },
      {
        id: 33, templateId: 1, field: "secondWeightDatetime", type: "weighment_detail", displayName: 'WT2 Datetime', row: null, col: 11, isIncluded: 1, font: "R"
      },
      {
        id: 34, templateId: 1, field: "remark", type: "weighment_detail", displayName: 'Rmrk', row: null, col: 1, isIncluded: 0, font: "R"
      },
      {
        id: 35, templateId: 1, field: "netWeight", type: "weighment_detail", displayName: 'Nt Wt', row: null, col: 13, isIncluded: 1, font: "R"
      },
      {
        id: 36, templateId: 1, field: "img1", type: "image-field", displayName: 'Image 1', row: null, col: null, isIncluded: 0, font: "R"
      },
      {
        id: 37, templateId: 1, field: "img2", type: "image-field", displayName: 'Image 2', row: null, col: null, isIncluded: 0, font: "R"
      },
      {
        id: 38, templateId: 1, field: "img3", type: "image-field", displayName: 'Image 3', row: null, col: null, isIncluded: 0, font: "R"
      },
      {
        id: 39, templateId: 1, field: "img4", type: "image-field", displayName: 'Image 4', row: null, col: null, isIncluded: 0, font: "R"
      }

    ],
    weighstring: [
      {
        stringName: "String13",
        totalChars: 8,
        variableLength: 0,
        type: "continuous",
        pollingCommand: null,
        baudRate: 2400,
        dataBits: 8,
        stopBits: 1,
        parity: "none",
        flowControl: "None",
        weightCharPosition1: 2,
        weightCharPosition2: 3,
        weightCharPosition3: 4,
        weightCharPosition4: 5,
        weightCharPosition5: 6,
        weightCharPosition6: null,
        startChar1: 2,
        startChar2: null,
        startChar3: null,
        startChar4: null,
        endChar1: 3,
        endChar2: "D",
        endChar3: "A",
        signCharPosition: 1,
        negativeSignValue: "-",
        delimeter: "\\\n"
      },
      {
        stringName: "Avery11",
        totalChars: 25,
        variableLength: 0,
        type: "polling",
        pollingCommand: "05",
        baudRate: 1200,
        dataBits: 7,
        stopBits: 1,
        parity: "even",
        flowControl: "None",
        weightCharPosition1: 3,
        weightCharPosition2: 4,
        weightCharPosition3: 5,
        weightCharPosition4: 6,
        weightCharPosition5: 7,
        weightCharPosition6: null,
        startChar1: 2,
        startChar2: null,
        startChar3: null,
        startChar4: null,
        endChar1: 3,
        endChar2: "D",
        endChar3: "A",
        signCharPosition: 1,
        negativeSignValue: "-",
        delimeter: "newline"
      },
      {
        stringName: "Avery8",
        totalChars: 19,
        variableLength: 0,
        type: "continuous",
        pollingCommand: null,
        baudRate: 1200,
        dataBits: 7,
        stopBits: 1,
        parity: "even",
        flowControl: "None",
        weightCharPosition1: 5,
        weightCharPosition2: 6,
        weightCharPosition3: 7,
        weightCharPosition4: 8,
        weightCharPosition5: 9,
        weightCharPosition6: null,
        startChar1: 2,
        startChar2: null,
        startChar3: null,
        startChar4: null,
        endChar1: 3,
        endChar2: "D",
        endChar3: "A",
        signCharPosition: 3,
        negativeSignValue: "-",
        delimeter: "\\\n"
      },
      {
        stringName: "Avery7",
        totalChars: 27,
        variableLength: 0,
        type: "continuous",
        pollingCommand: null,
        baudRate: 2400,
        dataBits: 7,
        stopBits: 1,
        parity: "even",
        flowControl: "None",
        weightCharPosition1: 5,
        weightCharPosition2: 6,
        weightCharPosition3: 7,
        weightCharPosition4: 8,
        weightCharPosition5: 9,
        weightCharPosition6: null,
        startChar1: 2,
        startChar2: null,
        startChar3: null,
        startChar4: null,
        endChar1: 3,
        endChar2: "D",
        endChar3: "A",
        signCharPosition: 3,
        negativeSignValue: "-",
        delimeter: "newline"
      },
      {
        stringName: "UNP",
        totalChars: 13,
        variableLength: 0,
        type: "continuous",
        pollingCommand: null,
        baudRate: 9600,
        dataBits: 8,
        stopBits: 1,
        parity: "None",
        flowControl: "None",
        weightCharPosition1: 3,
        weightCharPosition2: 4,
        weightCharPosition3: 5,
        weightCharPosition4: 6,
        weightCharPosition5: 7,
        weightCharPosition6: null,
        startChar1: 2,
        startChar2: null,
        startChar3: null,
        startChar4: null,
        endChar1: 3,
        endChar2: null,
        endChar3: null,
        signCharPosition: 2,
        negativeSignValue: "-",
        delimeter: null
      },
      {
        stringName: "String15",
        totalChars: 9,
        variableLength: 0,
        type: "continuous",
        pollingCommand: null,
        baudRate: 2400,
        dataBits: 8,
        stopBits: 1,
        parity: "None",
        flowControl: "None",
        weightCharPosition1: 2,
        weightCharPosition2: 3,
        weightCharPosition3: 4,
        weightCharPosition4: 5,
        weightCharPosition5: 6,
        weightCharPosition6: 7,
        startChar1: 2,
        startChar2: null,
        startChar3: null,
        startChar4: null,
        endChar1: 3,
        endChar2: null,
        endChar3: null,
        signCharPosition: 1,
        negativeSignValue: "-",
        delimeter: "newline"
      },        
    ],
    weighindicator: [],
    search_field: [{
      id: 1,
      displayName: "Supplier",
      inOutMode: "GENERIC",
      entryMode: "LIST_SOFT",
      enable: 1,
      fieldName: "supplier"
    }, {
        id: 2,
        displayName: "Material",
        inOutMode: "GENERIC",
        entryMode: "LIST_SOFT",
        enable: 1,
        fieldName: "supplier"
      }, {
        id: 3,
        displayName: "Transporter",
        inOutMode: "GENERIC",
        entryMode: "LIST_SOFT",
        enable: 1,
        fieldName: "supplier"
      }, {
        id: 4,
        displayName: "Customer",
        inOutMode: "GENERIC",
        entryMode: "LIST_SOFT",
        enable: 1,
        fieldName: "supplier"
      }],
    search_field_value: [
      //List of suppliers
      //{ id: 1, search_field_id: 1, code: '014', mValue: 'PARTY' },
      //{ id: 2, search_field_id: 1, code: '015', mValue: 'GENERAL' },
      //{ id: 3, search_field_id: 1, code: '07120', mValue: 'PUSHPAK STEEL IND.' },
      //{ id: 4, search_field_id: 1, code: '4460', mValue: 'SCHMOLZ + BICKENBACH (I( PVT.LTD' },
      //{ id: 5, search_field_id: 1, code: '4817', mValue: 'NIMCO ENGINEERING WORK' },
      //{ id: 6, search_field_id: 1, code: '50270', mValue: 'SHANTI STEEL INDUSTRIES' },
      //{ id: 7, search_field_id: 1, code: '70077', mValue: 'TOYOTA TSUSHO CORPORATION' },
      //{ id: 8, search_field_id: 1, code: '70590', mValue: 'DAYE SPECIAL STEEL CO. LTD.' },
      //{ id: 9, search_field_id: 1, code: '7120', mValue: 'PUSHPAK STEEL' },
      //{ id: 10, search_field_id: 1, code: '71263', mValue: 'SPECIALITY STEEL UK LTD.' },
      //{ id: 11, search_field_id: 1, code: '80008', mValue: 'HINDALCO INDUSTRIES LTD' },
      //{ id: 12, search_field_id: 1, code: '80013', mValue: 'KALYANI STEELS LTD.' },
      //{ id: 13, search_field_id: 1, code: '80018', mValue: 'OM FORGING & ENGG. PVT.LTD' },
      //{ id: 14, search_field_id: 1, code: '80021', mValue: 'R.L.STEELS & ENERGY LTD' },
      //{ id: 15, search_field_id: 1, code: '80041', mValue: 'PCK BUDERUS INDIA SPECIAL STEELS' },
      //{ id: 16, search_field_id: 1, code: '80042', mValue: 'SMITA STEELS ROLLING MILLS PVT LTD' },
      //{ id: 17, search_field_id: 1, code: '80064', mValue: 'POONA PROFILES PVT. LTD.' },
      //{ id: 18, search_field_id: 1, code: '80084', mValue: 'GOEL STEEL COMPANY' },
      //{ id: 19, search_field_id: 1, code: '80089', mValue: 'JSW STEEL LTD.' },
      //{ id: 20, search_field_id: 1, code: '80104', mValue: 'MAHINDRA STEEL' },
      //{ id: 21, search_field_id: 1, code: '80121', mValue: 'MSSSPL' },
      //{ id: 22, search_field_id: 1, code: '80125', mValue: 'MUKAND SUMI METAL PROCESSING LTD.' },
      //{ id: 23, search_field_id: 1, code: '80126', mValue: 'UTTAM VALUE STEELS LTD.' },
      //{ id: 24, search_field_id: 1, code: '80127', mValue: 'SAARLOHA ADVANCED MATERIALS PVT.LTD' },
      //{ id: 25, search_field_id: 1, code: '80129', mValue: 'VARDHMAN SPECIAL STEELS LTD' },
      //{ id: 26, search_field_id: 1, code: '80139', mValue: 'JAYASWAL NECO IND.LTD.' },
      //{ id: 27, search_field_id: 1, code: '80141', mValue: 'OM STEEL ENTERPRISES' },
      //{ id: 28, search_field_id: 1, code: '80145', mValue: 'SLR METALIKS LTD' },
      //{ id: 29, search_field_id: 1, code: '80148', mValue: 'CENTURY EXTRUSIONS LTD.' },
      //{ id: 30, search_field_id: 1, code: '80153', mValue: 'MAGNUM STEEL' },
      //{ id: 31, search_field_id: 1, code: '80156', mValue: 'TATA STEEL LONG PRODUCT' },

      ////List of Materials
      //{ id: 32, search_field_id: 2, code: '001', mValue: 'STEEL BAR' },
      //{ id: 33, search_field_id: 2, code: '002', mValue: 'FLASH' },
      //{ id: 34, search_field_id: 2, code: '005', mValue: 'CIVIL' },
      //{ id: 35, search_field_id: 2, code: '006', mValue: 'HFD 1/2' },
      //{ id: 36, search_field_id: 2, code: '007', mValue: 'GAS' },
      //{ id: 37, search_field_id: 2, code: '008', mValue: 'KEROSENE' },
      //{ id: 38, search_field_id: 2, code: '009', mValue: 'CRANE/JCB' },
      //{ id: 39, search_field_id: 2, code: '010', mValue: 'PETROL/DIESEL' },
      //{ id: 40, search_field_id: 2, code: '011', mValue: 'SHIPPING' },
      //{ id: 41, search_field_id: 2, code: '012', mValue: 'GENERAL STORE' },
      //{ id: 42, search_field_id: 2, code: '013', mValue: 'WATER' },
      //{ id: 43, search_field_id: 2, code: '014', mValue: 'DIE BLOCK' },
      //{ id: 44, search_field_id: 2, code: '015', mValue: 'ALUMINIUM' },
      //{ id: 45, search_field_id: 2, code: '016', mValue: 'CANTEEN' },
      //{ id: 46, search_field_id: 2, code: '017', mValue: 'CONTAINER' },
      //{ id: 47, search_field_id: 2, code: '018', mValue: 'OTHER' },

      ////List of transporters
      //{ id: 48, search_field_id: 3, code: '07120', mValue: 'PUSHPAK STEEL IND.' },
      //{ id: 49, search_field_id: 3, code: '40000', mValue: 'VENDOR TRANSPORT ( STORES )' },
      //{ id: 50, search_field_id: 3, code: '40002', mValue: 'ARC ( ASSOCIATED ROAD CARRIERS )' },
      //{ id: 51, search_field_id: 3, code: '40020', mValue: 'BHOSALE TEMPO SERVICE' },
      //{ id: 52, search_field_id: 3, code: '40022', mValue: 'BUNTI TEMPO SERVICE' },
      //{ id: 53, search_field_id: 3, code: '40029', mValue: 'DURGA CARRYING CORPORATION' },
      //{ id: 54, search_field_id: 3, code: '40037', mValue: 'DHIRAJ TRANSPORT' },
      //{ id: 55, search_field_id: 3, code: '40039', mValue: 'ECONOMICS TRANSPORT ORGANIZIATION' },
      //{ id: 56, search_field_id: 3, code: '40042', mValue: 'GIR MOVERS LTD' },
      //{ id: 57, search_field_id: 3, code: '40051', mValue: 'HUNDEKKARI GOODS TRANSPORT SERVICE' },
      //{ id: 58, search_field_id: 3, code: '40059', mValue: 'JAGTAP GOODS TRANSPORT' },
      //{ id: 59, search_field_id: 3, code: '40079', mValue: 'LOKSEVA GOODS CARRIERS' },
      //{ id: 60, search_field_id: 3, code: '40083', mValue: 'MK MAHENDALE TRANSPORT' },
      //{ id: 61, search_field_id: 3, code: '40089', mValue: 'MAULI KRUPA TRANSPORT' },
      //{ id: 62, search_field_id: 3, code: '40092', mValue: 'M NUSSERWANJI AND COMPANY' },
      //{ id: 63, search_field_id: 3, code: '40101', mValue: 'NAVKHANDENATH TRANSPORT' },
      //{ id: 64, search_field_id: 3, code: '40105', mValue: 'POONA RANCHI ROADWAYS LOGISTICS P LTD' },
      //{ id: 65, search_field_id: 3, code: '40109', mValue: 'SATYAM ROADLINES' },
      //{ id: 66, search_field_id: 3, code: '40110', mValue: 'PRAKASH TRANSPORT COMPANY' },
      //{ id: 67, search_field_id: 3, code: '40119', mValue: 'Party Transaport ( Shipping )' },
      //{ id: 68, search_field_id: 3, code: '40120', mValue: 'RAVINDER TRANSPORT SERVICES' },
      //{ id: 69, search_field_id: 3, code: '40124', mValue: 'RUKARI TRANSLINE' },
      //{ id: 70, search_field_id: 3, code: '40131', mValue: 'SOUTH EASTERN CARRIERS P LTD' },
      //{ id: 71, search_field_id: 3, code: '40132', mValue: 'SHRI REVENSIDHA TRANSPORT' },
      //{ id: 72, search_field_id: 3, code: '40134', mValue: 'SOURABH TEMPO SERVICE' },
      //{ id: 73, search_field_id: 3, code: '40135', mValue: 'SANTOSH TRANSPORT' },
      //{ id: 74, search_field_id: 3, code: '40140', mValue: 'SHRI MAYURESHWAR TRANSPORT' },
      //{ id: 75, search_field_id: 3, code: '40141', mValue: 'SCC CARGO P LTD' },
      //{ id: 76, search_field_id: 3, code: '40171', mValue: 'SHREE VIJAYLAXMI TRANSPORT' },
      //{ id: 77, search_field_id: 3, code: '40173', mValue: 'SHRINATH TRANSPORT' },
      //{ id: 78, search_field_id: 3, code: '40174', mValue: 'SHREE GURUKRUPA TRANSPORT' },
      //{ id: 79, search_field_id: 3, code: '40185', mValue: 'THORAT TRANSPORT' },
      //{ id: 80, search_field_id: 3, code: '40196', mValue: 'V N RUKARI AND SONS' },
      //{ id: 81, search_field_id: 3, code: '40209', mValue: 'DEEPAK TRANSPORT' },
      //{ id: 82, search_field_id: 3, code: '40219', mValue: 'PRANAV TEMPO SERVICE' },
      //{ id: 83, search_field_id: 3, code: '40233', mValue: 'SUPER TRANSPORT SERVICE' },
      //{ id: 84, search_field_id: 3, code: '40237', mValue: 'JAI BALAJI TRANSPORT' },
      //{ id: 85, search_field_id: 3, code: '40267', mValue: 'LEROY TRANSPORT' },
      //{ id: 86, search_field_id: 3, code: '40268', mValue: 'REACH CARGO MOVERS P LTD' },
      //{ id: 87, search_field_id: 3, code: '40278', mValue: 'ASHISH TRANSPORT' },
      //{ id: 88, search_field_id: 3, code: '40293', mValue: 'MAULI KRUPA TEMPO SERVICES' },
      //{ id: 89, search_field_id: 3, code: '40323', mValue: 'VAIJNATH TRANSPORT' },
      //{ id: 90, search_field_id: 3, code: '40347', mValue: 'MALI TRANSPORT' },
      //{ id: 91, search_field_id: 3, code: '40377', mValue: 'RAJESHWAR TRANSPORT' },
      //{ id: 92, search_field_id: 3, code: '40398', mValue: 'DHANSHREE TRANSPORT' },
      //{ id: 93, search_field_id: 3, code: '40408', mValue: 'BIC LOGISTICS VENTURES LTD' },
      //{ id: 94, search_field_id: 3, code: '40417', mValue: 'SAHIL TEMPO SERVICES' },
      //{ id: 95, search_field_id: 3, code: '40418', mValue: 'CHETAK LOCISTICS LTD' },
      //{ id: 96, search_field_id: 3, code: '40419', mValue: 'MEGA FREIGHT MOVERS LTD' },
      //{ id: 97, search_field_id: 3, code: '40422', mValue: 'BARAMATI ROADLINES' },
      //{ id: 98, search_field_id: 3, code: '40427', mValue: 'VISHAL TRANSPORT' },
      //{ id: 99, search_field_id: 3, code: '40432', mValue: 'SAI TRANSPORT' },
      //{ id: 100, search_field_id: 3, code: '40433', mValue: 'R D TRANSPORT' },
      //{ id: 101, search_field_id: 3, code: '40437', mValue: 'RAGHAV TRANSPORT' },
      //{ id: 102, search_field_id: 3, code: '40442', mValue: 'ROYAL TRANSPORT' },
      //{ id: 103, search_field_id: 3, code: '40447', mValue: 'SARCO ROADLINES P LTD' },
      //{ id: 104, search_field_id: 3, code: '40452', mValue: 'ATHARVA TRANSPORT' },
      //{ id: 105, search_field_id: 3, code: '40453', mValue: 'VHORA LOGISTICS' },
      //{ id: 106, search_field_id: 3, code: '40454', mValue: 'SARASWATI TRANSPORT COMPANY' },
      //{ id: 107, search_field_id: 3, code: '40467', mValue: 'VENKATESHWARA ROADLINES' },
      //{ id: 108, search_field_id: 3, code: '40469', mValue: 'SHREE ATHARAV TRANSPORT' },
      //{ id: 109, search_field_id: 3, code: '40472', mValue: 'ABC LOGISTICS' },
      //{ id: 110, search_field_id: 3, code: '40477', mValue: 'DURGA TRANSPORT' },
      //{ id: 111, search_field_id: 3, code: '40483', mValue: 'POOJA TRANSPORT' },
      //{ id: 112, search_field_id: 3, code: '40487', mValue: 'GLOBE ECO LOGISTICS' },
      //{ id: 113, search_field_id: 3, code: '40488', mValue: 'NORTH EASTERN CARRYING CORP' },
      //{ id: 114, search_field_id: 3, code: '40492', mValue: 'DUNGARPUR GOLDEN TRANSPORT' },
      //{ id: 115, search_field_id: 3, code: '40503', mValue: 'CHOTHAVE TRANSPORT' },
      //{ id: 116, search_field_id: 3, code: '40504', mValue: 'SAI TRANSPORT .' },
      //{ id: 117, search_field_id: 3, code: '40505', mValue: 'TYAGI TRANSPORT' },
      //{ id: 118, search_field_id: 3, code: '40506', mValue: 'AXPRESS LOGISTICS INDIA P LTD' },
      //{ id: 119, search_field_id: 3, code: '40508', mValue: 'SHUBHAM ROADLINES' },
      //{ id: 120, search_field_id: 3, code: '40509', mValue: 'SARVADNYA ENTERPRISE' },
      //{ id: 121, search_field_id: 3, code: '40512', mValue: 'OM SAKTHI' },
      //{ id: 122, search_field_id: 3, code: '40517', mValue: 'AWAGAMAN LOGISTICS' },
      //{ id: 123, search_field_id: 3, code: '40519', mValue: 'BHOSALE TRANSPORT' },
      //{ id: 124, search_field_id: 3, code: '40520', mValue: 'ADITYA TRANSPORT' },
      //{ id: 125, search_field_id: 3, code: '40521', mValue: 'SURYA TRANSPORT CARRYING CORP' },
      //{ id: 126, search_field_id: 3, code: '40523', mValue: 'SHRI SWAMI SAMARTH LOGISTICS' },
      //{ id: 127, search_field_id: 3, code: '40524', mValue: 'SAGAR ERECTORS' },
      //{ id: 128, search_field_id: 3, code: '40525', mValue: 'PCC LOGISTICS LTD' },
      //{ id: 129, search_field_id: 3, code: '40526', mValue: 'RAJKAMAL TRANSPORT' },
      //{ id: 130, search_field_id: 3, code: '40527', mValue: 'KAPIL ROADWAYS P LTD' },
      //{ id: 131, search_field_id: 3, code: '40529', mValue: 'SHRAVAN TRANSPORT' },
      //{ id: 132, search_field_id: 3, code: '40530', mValue: 'MAA ANNAPURNA TRANSPORT AGENCY' },
      //{ id: 133, search_field_id: 3, code: '40533', mValue: 'SHREYA ENTERPRISE' },
      //{ id: 134, search_field_id: 3, code: '40534', mValue: 'VIVEK TRANSPORT' },
      //{ id: 135, search_field_id: 3, code: '40535', mValue: 'ECO TRANS LOGISTICS' },
      //{ id: 136, search_field_id: 3, code: '40546', mValue: 'VAISHNAVI TRANSPORT' },
      //{ id: 137, search_field_id: 3, code: '40547', mValue: 'SAFEXPRESS P LTD' },
      //{ id: 138, search_field_id: 3, code: '40548', mValue: 'RAJYOG TRANSPORT' },
      //{ id: 139, search_field_id: 3, code: '40549', mValue: 'INLAND WORLD LOGISTICS P LTD' },
      //{ id: 140, search_field_id: 3, code: '40550', mValue: 'SHIVSHAMBHO TRANSPORT' },
      //{ id: 141, search_field_id: 3, code: '40552', mValue: 'ASHOKDEEP ROADWAYS' },
      //{ id: 142, search_field_id: 3, code: '40553', mValue: 'KADAM TRANSPORT' },
      //{ id: 143, search_field_id: 3, code: '40554', mValue: 'VICKY ROADWAYS P LTD' },
      //{ id: 144, search_field_id: 3, code: '40555', mValue: 'PITHAMPUR BOMBAY ROAD WAYS' },
      //{ id: 145, search_field_id: 3, code: '40557', mValue: 'JFK TRANSPORT' },
      //{ id: 146, search_field_id: 3, code: '40558', mValue: 'SADGURU LOGISTICS' },
      //{ id: 147, search_field_id: 3, code: '40559', mValue: 'TEJ CARRIERS P LTD' },
      //{ id: 148, search_field_id: 3, code: '40560', mValue: 'BHARATH SWIFT LOGISTICS P LTD' },
      //{ id: 149, search_field_id: 3, code: '40561', mValue: 'CHANDRA TRANSPORT CORP' },
      //{ id: 150, search_field_id: 3, code: '40562', mValue: 'SANKET TRANSPORT' },
      //{ id: 151, search_field_id: 3, code: '40563', mValue: 'ADARSH TRANSPORT' },
      //{ id: 152, search_field_id: 3, code: '40564', mValue: 'BHAGYODAYA TRANSPORT COMPANT' },
      //{ id: 153, search_field_id: 3, code: '40565', mValue: 'BOMBAY GOODS FREIGHT CARRIERS' },
      //{ id: 154, search_field_id: 3, code: '40566', mValue: 'CHINTAMANI TRANSPORT SERVICES' },
      //{ id: 155, search_field_id: 3, code: '40567', mValue: 'ICM LOGISTICS P LTD' },
      //{ id: 156, search_field_id: 3, code: '40569', mValue: 'SHINDE TRANSPORT' },
      //{ id: 157, search_field_id: 3, code: '40570', mValue: 'SWRAJ TRANSPORT' },
      //{ id: 158, search_field_id: 3, code: '40571', mValue: 'GANESH TPT' },
      //{ id: 159, search_field_id: 3, code: '40573', mValue: 'SHIV MALHAR TPT' },
      //{ id: 160, search_field_id: 3, code: '40576', mValue: 'MARTAND TPT' },
      //{ id: 161, search_field_id: 3, code: '40577', mValue: 'SHRIRAM TRANSPORT' },
      //{ id: 162, search_field_id: 3, code: '40578', mValue: 'TIMES SQUARE LOOGISTIS' },
      //{ id: 163, search_field_id: 3, code: '40580', mValue: 'IDEAL TRANWAYS (PUNE)' },
      //{ id: 164, search_field_id: 3, code: '40581', mValue: 'SAI SHYAM TRANSPORT' },
      //{ id: 165, search_field_id: 3, code: '40582', mValue: 'ASSAM BOMBAY CARRIERS P LTD' },
      //{ id: 166, search_field_id: 3, code: '40583', mValue: 'Tirupati Transline & Company' },
      //{ id: 167, search_field_id: 3, code: '40584', mValue: 'SHREE GANESH TRANSPORT SERVICE' },
      //{ id: 168, search_field_id: 3, code: '40585', mValue: 'SHRI BHAIRAVNATH TRANSPORT' },
      //{ id: 169, search_field_id: 3, code: '40586', mValue: 'SHREE TRANSPORT' },
      //{ id: 170, search_field_id: 3, code: '40587', mValue: 'SHIVANI CARRIERS P LTD' },
      //{ id: 171, search_field_id: 3, code: '40588', mValue: 'RIVIGO SERVICES P LTD (Haryana)' },
      //{ id: 172, search_field_id: 3, code: '40589', mValue: 'RIVIGO SERVICES P LTD (Tamil nadu)' },
      //{ id: 173, search_field_id: 3, code: '40590', mValue: 'RIVIGO SERVICES P LTD (Karnataka )' },
      //{ id: 174, search_field_id: 3, code: '40591', mValue: 'RIVIGO SERVICES P LTD (Madhya Pradesh)' },
      //{ id: 175, search_field_id: 3, code: '40592', mValue: 'RIVIGO SERVICES P LTD (Maharashtra)' },
      //{ id: 176, search_field_id: 3, code: '40593', mValue: 'ALL India Transport Service' },
      //{ id: 177, search_field_id: 3, code: '40594', mValue: 'YOGESH TEMPO SERVICE' },
      //{ id: 178, search_field_id: 3, code: '40596', mValue: 'KRISHANA TPT' },
      //{ id: 179, search_field_id: 3, code: '40597', mValue: 'MAULI KRUPA TPT' },
      //{ id: 180, search_field_id: 3, code: '40602', mValue: 'SUNTEK AXPRESS LOGISTICS' },
      //{ id: 181, search_field_id: 3, code: '4460', mValue: 'SCHMOLZ + BICKENBACH (I( PVT.LTD' },
      //{ id: 182, search_field_id: 3, code: '4817', mValue: 'NIMCO ENGINEERING WORK' },
      //{ id: 183, search_field_id: 3, code: '50270', mValue: 'SHANTI STEEL INDUSTRIES' },
      //{ id: 184, search_field_id: 3, code: '70077', mValue: 'TOYOTA TSUSHO COR.' },
      //{ id: 185, search_field_id: 3, code: '70590', mValue: 'DAYA STEEL LTD' },
      //{ id: 186, search_field_id: 3, code: '7120', mValue: 'PUSHPAK STEEL' },
      //{ id: 187, search_field_id: 3, code: '71263', mValue: 'SPECIALITY STEEL UK LTD.' },
      //{ id: 188, search_field_id: 3, code: '80008', mValue: 'HINDALCO INDUSTRIES LTD' },
      //{ id: 189, search_field_id: 3, code: '80013', mValue: 'KALYANI STEEL LTD' },
      //{ id: 190, search_field_id: 3, code: '80018', mValue: 'OM FORGING & ENGG. PVT.LTD' },
      //{ id: 191, search_field_id: 3, code: '80021', mValue: 'R.L.STEELS & ENERGY LTD' },
      //{ id: 192, search_field_id: 3, code: '80041', mValue: 'PCK BSSPL' },
      //{ id: 193, search_field_id: 3, code: '80042', mValue: 'SMITA STEELS ROLLING MILLS PVT LTD' },
      //{ id: 194, search_field_id: 3, code: '80064', mValue: 'POONA PROFILE PVT LTD' },
      //{ id: 195, search_field_id: 3, code: '80084', mValue: 'GOEL STEEL COMPANY' },
      //{ id: 196, search_field_id: 3, code: '80089', mValue: 'JSW STEEL LTD' },
      //{ id: 197, search_field_id: 3, code: '80109', mValue: 'TATA SPONGE IRON LTD' },
      //{ id: 198, search_field_id: 3, code: '80121', mValue: 'MAHINDRA SANYO SPECIAL STEEL' },
      //{ id: 199, search_field_id: 3, code: '80125', mValue: 'MUKAND SUMI METAL PROC' },
      //{ id: 200, search_field_id: 3, code: '80127', mValue: 'SAMPL' },
      //{ id: 201, search_field_id: 3, code: '80129', mValue: 'VARDHMAN SPECIAL STEELS LTD' },
      //{ id: 202, search_field_id: 3, code: '80139', mValue: 'Jayaswal Neco Ind.Ltd' },
      //{ id: 203, search_field_id: 3, code: '80141', mValue: 'OM STEEL ENTERPRISES' },
      //{ id: 204, search_field_id: 3, code: '80145', mValue: 'SLR METALIKS LTD' },
      //{ id: 205, search_field_id: 3, code: '80148', mValue: 'ENTURY EXTRUSIONS LTD.' },
      //{ id: 206, search_field_id: 3, code: '80151', mValue: 'TATA SPONGE IRON LTD.' },
      //{ id: 207, search_field_id: 3, code: '80153', mValue: 'MAGNUM STEEL' },
      //{ id: 208, search_field_id: 3, code: '80156', mValue: 'TATA STEEL LONG PRODUCT' },
    ],
    help: [
      { id: "DATA_SETUP", content: '<!DOCTYPE html PUBLIC " -//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> <html xmlns="http://www.w3.org/1999/xhtml"> <head> <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" /> <title>Apconic Weighment Software</title> <style type="text/css"> body { margin:0 auto; margin-top:5px; } /* ----- HEADER ----- */ #header { background-color:#00a4ff; text-align:center; font-family:Verdana; font-weight:bold; font-size:15px; } /* ----- SUMMARY ----- */ #summary { background-color:#6ecbff; margin-top:5px; min-height:30px; /* for modern browsers */ height:auto !important; /* for modern browsers */ font-family:Helvetica; font-size:12px; padding: 12px; } /* ----- MAIN CONTENT ----- */ #content { background-color:#FFFFFF; margin-top:5px; min-height:250px; /* for modern browsers */ height:auto !important; /* for modern browsers */ font-family:Helvetica; font-size:12px; ; } /* ----- FOOTER ----- */ #footer { height:20px; background-color:#43b7f7; margin-top:5px; font-family: Verdana; font-size:11px; text-align: center; } </style> </head> <body> <div id="header"> Data Setup </div> <div id="summary"> This is a multi-tab form and very important part of software setup. All data fields, their types, inbound/outbound functionality and formula fields are defined here. Please note that no changes to data setup are allowed once there are weighment records captured in the system. </div> <div id="content"> <table> <tr> <td width="25%" valign="top"><b>Features:</b></td> <td>This tab is used to enable/disable important functionality of the application.</td> </tr> <tr> <td valign="top"><b>Tracking Field:</b></td> <td>The tracking field is used to recall the weighment record for subsequent weighments. Vehicle Number and Weigh Slip Number are the most frequently used tracking fields. </td> </tr> <tr> <td valign="top"><b>Search Fields:</b></td> <td> Search fields are the data entry fields that can also be used during reports / search to filter the records. This tab is used to configure the number of search fields, their display names and their data entry types. </td> </tr> <tr> <td valign="top"><b>System Constants:</b></td> <td> System constants are application level numeric fields like Rate, Parking Charges, Binding Material Percentage, etc. Generally these fields are used in additional fields that are of type formula. </td> </tr> <!--<tr> <td valign="top"><b>Additional Fields:</b></td> <td> Additional Fields are data entry fields. The difference with search fields is that the data entry type can also be numeric or formula in addition to the options available to search fields. It is important to note that additional fields cannot be used to filter the weighment records during search / reports. </td> </tr>--> </table> </div> <div id="footer" class="foot"><span style="display:inline-block; vertical-align:middle">Copyright &copy; 2014 Apconic Software Pvt. Ltd.</span></div> </body> </html>'}
    ]
  },

  sqlStmt: {
    app_data: "INSERT INTO app_data(field, mValue) VALUES('{field}', '{mValue}')",
    app_user: "INSERT INTO app_user(id, fullname, username, password, status, role) VALUES('{id}', '{fullname}', '{username}', '{password}', '{status}', '{role}')",
    permission: "INSERT INTO permission(id, permission) VALUES({id}, '{permission}')",
    user_permission: "INSERT INTO user_permission(userid, permissionid) VALUES({userid}, {permissionid})",
    ticket_template: "INSERT INTO ticket_template(id, name, applicableTo, printerType, defaultPrinter, labelLength, copiesPerPrint, alignment, width, font, fontSize, operatingType) VALUES({id}, '{name}', '{applicableTo}', '{printerType}', '{defaultPrinter}', {labelLength}, {copiesPerPrint}, '{alignment}', {width}, '{font}', {fontSize}, '{operatingType}')",
    template_detail: "INSERT INTO template_detail(id, templateId, field, type, displayName, row, col, isIncluded, font) VALUES({id}, {templateId}, '{field}', '{type}', '{displayName}', {row}, {col}, {isIncluded}, '{font}')",
    weighindicator: "INSERT INTO weighindicator(id, weighstring, port, status, measuringUnit, decimalPoint, type, httpType, comPort, wiName, ipAddress) VALUES({id}, '{weighstring}', {port}, '{status}', '{measuringUnit}', {decimalPoint}, '{type}', '{httpType}', '{comPort}', '{wiName}', '{ipAddress}')",
    weighstring: "INSERT INTO weighstring (stringName, totalChars, variableLength, type, pollingCommand, baudRate, dataBits, stopBits, parity, flowControl, weightCharPosition1, weightCharPosition2, weightCharPosition3, weightCharPosition4, weightCharPosition5, weightCharPosition6, startChar1, startChar2, startChar3, startChar4, endChar1, endChar2, endChar3, signCharPosition, negativeSignValue) VALUES ('{stringName}', {totalChars}, {variableLength}, '{type}', '{pollingCommand}', '{baudRate}', {dataBits}, {stopBits}, '{parity}', '{flowControl}', {weightCharPosition1}, {weightCharPosition2}, {weightCharPosition3}, {weightCharPosition4}, {weightCharPosition5}, {weightCharPosition6}, '{startChar1}', '{startChar2}', '{startChar3}', '{startChar4}', '{endChar1}', '{endChar2}', '{endChar3}', {signCharPosition}, '{negativeSignValue}')",
    search_field: "INSERT INTO search_field(id, displayName, entryMode, inOutMode) VALUES({id}, '{displayName}', '{entryMode}', '{inOutMode}')",
    search_field_value: "INSERT INTO search_field_value(id, search_field_id, mValue, code) VALUES({id}, {search_field_id}, '{mValue}', '{code}')",
    help: "INSERT INTO help(id, content) VALUES('{id}', '{content}')"
  },

  envStmts: {
  }
  
})
